### ISSUE TITLE
+/-mode event data not correct?

### ISSUE THREAD

**Issue by sudojunior** [Sven65/Carp#2]
https://gist.github.com/PlayTheFallen/b1d9ba838e0ec7d850a2902ed2ea35f8#file-ircbridge-js-L35-L42
Data within the event is limited, log...

```js
        guild.send(`**${from} gives **${user.info.nick}** the flag(s) ${modes.join(', ')}`)
                                                 ^

TypeError: Cannot read property 'nick' of undefined
    at Channel.channel.on (C:\Users\Morgan\Documents\GitHub\carpbot\test\test.js:36:50)
    at emitOne (events.js:115:13)
    at Channel.emit (events.js:210:7)
    at Channel.handleMode (C:\Users\Morgan\Documents\GitHub\carpbot\node_modules\carp-irc\src\Structures\Channel.js:213:9)
    at Channel.handleRaw (C:\Users\Morgan\Documents\GitHub\carpbot\node_modules\carp-irc\src\Structures\Channel.js:166:10)
    at Client.on.message (C:\Users\Morgan\Documents\GitHub\carpbot\node_modules\carp-irc\src\Structures\Client\index.js:341:16)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at iterator (C:\Users\Morgan\Documents\GitHub\carpbot\node_modules\carp-irc\src\Structures\Client\index.js:503:8)
    at Array.forEach (native)```

**Comment by Sven65** [comment]
The `+mode` and `-mode` events emit a single object with the data inside.
